import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ConvexClientProviders from "@/providers/ConvexClientProviders";
import { ClerkLoaded, ClerkLoading } from "@clerk/nextjs";
import LoadingLogo from "@/components/shared/LoadingLogo";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConvexClientProviders>
          <ClerkLoading>
            <LoadingLogo />
          </ClerkLoading>
          <ClerkLoaded>{children}</ClerkLoaded>
        </ConvexClientProviders>
      </body>
    </html>
  );
}
